//
//  Movie+CoreDataClass.swift
//  Movie
//
//  Created by Marcelo Mogrovejo on 5/31/17.
//  Copyright © 2017 Marcelo Mogrovejo. All rights reserved.
//

import UIKit
import CoreData

@objc(Movie)
class Movie: NSManagedObject {

    internal func getMovieInfo(title: String, context: NSManagedObjectContext) -> Movie? {
        
        // Movie.fetchRequest() comes from Movie+CoreDataProperties.swift file generated by xcode 10 behind the scene
        let request: NSFetchRequest<Movie> = Movie.fetchRequest()
        request.predicate = NSPredicate(format: "title = %@", title)
        
        do {
            let results = try context.fetch(request)
            
            if results.count > 0 {
                return results.first
            } else {
                return nil
            }
        } catch {
            fatalError("Error fetching movie info")
        }
        
        return nil
    }
    
}
